project:
  type: website
  output-dir: ../docs

website:
  title: "BIDS Derivatives"
  navbar:
    left:
      - href: https://github.com/effigies/bids-derivatives-2023
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

